import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, Bookmark, BriefcaseBusiness, BrainCircuit, CheckCircle2, CircleHelp, FileText, GraduationCap, LogIn, LogOut, MessageCircle, Mic, Plus, Search, Send, Sparkles, Target, Trash2, UserRound, X } from "lucide-react";
import "./App.css";

const API = "/api";
const navItems = [
  ["matcher","Job matcher"],["jobs","Job listings"],["resume","Resume & ATS"],["roadmap","Learning roadmap"],
  ["interview","Interview prep"],["chat","Career chatbot"],["tracker","Applications"],["dashboard","My dashboard"]
];
async function request(path, options = {}, token = "") {
  const headers = { ...(options.headers || {}) };
  if (token) headers.Authorization = "Bearer " + token;
  const response = await fetch(API + path, { ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.detail || "Request failed. Please try again.");
  return data;
}
function Tags({ items = [], variant = "matched" }) {
  return items?.length ? <div className="tags">{items.map(item => <span className={`tag ${variant}`} key={item}>{item}</span>)}</div> : <span className="muted small">None identified</span>;
}
function PanelTitle({ icon: Icon, eyebrow, title, description }) {
  return <div className="feature-title"><span className="feature-icon"><Icon size={21}/></span><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div></div>;
}
function JobCard({ job, onSave, saved, onCompare, compared }) {
  return <article className="job-card">
    <div className="job-top"><div className="job-icon"><BriefcaseBusiness size={21}/></div><div className="job-title"><h3>{job.title}</h3><p>{job.company}</p><span className="location">{job.location} · {job.experience}</span><small className="salary">{job.salary_min ? `₹${(job.salary_min/100000).toFixed(1)}–₹${(job.salary_max/100000).toFixed(1)} LPA · ${job.work_mode}` : ""}</small></div><div className="score"><strong>{job.match_score}%</strong><span>match</span></div></div>
    <div className="track"><div className="track-fill" style={{width:`${job.match_score}%`}}/></div><p className="description">{job.description}</p>
    <div className="score-breakdown"><span>Skill overlap <b>{job.skill_score}%</b></span><span>Text similarity <b>{job.semantic_score}%</b></span></div>
    <section className="skill-section"><h4><CheckCircle2 size={15}/> Matching skills</h4><Tags items={job.matched_skills}/></section>
    <section className="skill-section"><h4><Sparkles size={15}/> Skills to develop</h4><Tags items={job.missing_skills} variant="missing"/></section>
    <div className="job-actions"><button className="secondary-button" onClick={()=>onSave(job)}><Bookmark size={15}/>{saved ? "Saved" : "Save job"}</button><label className="compare-check"><input type="checkbox" checked={compared} onChange={()=>onCompare(job)}/> Compare</label></div>
  </article>;
}
function AuthPanel({ onAuth, onClose }) {
  const [mode,setMode]=useState("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError("");try{const data=await request("/auth/"+mode,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password})});onAuth(data);}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}><X size={18}/></button><div className="feature-icon"><UserRound size={22}/></div><h2>{mode==="login"?"Welcome back":"Create your account"}</h2><p className="muted">Save matches, keep history, and track applications.</p>{mode==="register"&&<label>Your name<input required value={name} onChange={e=>setName(e.target.value)} maxLength="80"/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required type="password" minLength="8" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></label>{error&&<p className="error-message">{error}</p>}<button className="submit-button" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button><button className="text-button" type="button" onClick={()=>{setMode(mode==="login"?"register":"login");setError("")}}>{mode==="login"?"New here? Create an account":"Already have an account? Sign in"}</button><small className="muted">Use a unique password. For production, set APP_SECRET_KEY and use persistent storage.</small></form></div>;
}
export default function App() {
  const [tab,setTab]=useState("matcher"),[profile,setProfile]=useState(""),[resume,setResume]=useState(null),[matches,setMatches]=useState([]),[candidateSkills,setCandidateSkills]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[hasSearched,setHasSearched]=useState(false);
  const [token,setToken]=useState(()=>localStorage.getItem("jm_token")||""),[user,setUser]=useState(null),[showAuth,setShowAuth]=useState(false),[toast,setToast]=useState("");
  const [roleFilter,setRoleFilter]=useState(""),[skillFilter,setSkillFilter]=useState(""),[locationFilter,setLocationFilter]=useState(""),[remoteOnly,setRemoteOnly]=useState(false),[salaryMin,setSalaryMin]=useState("0"),[salaryMax,setSalaryMax]=useState("1000000"),[jobCatalog,setJobCatalog]=useState([]),[compared,setCompared]=useState([]);
  const [analysis,setAnalysis]=useState(null),[roadRole,setRoadRole]=useState("Full Stack Developer"),[roadSkills,setRoadSkills]=useState("Python, SQL, Git"),[roadmap,setRoadmap]=useState(null),[interviewRole,setInterviewRole]=useState("Software Developer"),[interview,setInterview]=useState(null),[quizAnswers,setQuizAnswers]=useState({});
  const [chatInput,setChatInput]=useState(""),[chatMessages,setChatMessages]=useState([{from:"bot",text:"Hi! I can help with resumes, job search strategy, skill gaps, and interview preparation. What are you working toward?"}]);
  const [dashboard,setDashboard]=useState(null),[appTitle,setAppTitle]=useState(""),[appCompany,setAppCompany]=useState(""),[appStatus,setAppStatus]=useState("Applied"),[applications,setApplications]=useState([]);
  useEffect(()=>{if(token){request("/auth/me",{},token).then(d=>setUser(d.user)).catch(()=>{localStorage.removeItem("jm_token");setToken("");setUser(null)})}},[]);
  useEffect(()=>{request("/jobs").then(setJobCatalog).catch(()=>{})},[]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(""),3500);return()=>clearTimeout(id)}},[toast]);
  async function findMatches(e){e?.preventDefault();setLoading(true);setError("");try{const form=new FormData();form.append("profile_text",profile);if(resume)form.append("resume",resume);const d=await request("/match",{method:"POST",body:form});setMatches(d.matches);setCandidateSkills(d.candidate_skills);setHasSearched(true);setCompared([]);setTab("matcher");if(token)request("/history",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile_text:profile,matches:d.matches})},token).catch(()=>{});}catch(err){setError(err.message)}finally{setLoading(false)}}
  async function searchJobs(){try{const p=new URLSearchParams();if(roleFilter)p.set("role",roleFilter);if(skillFilter)p.set("skills",skillFilter);if(locationFilter)p.set("location",locationFilter);if(remoteOnly)p.set("remote","true");p.set("salary_min",salaryMin||"0");p.set("salary_max",salaryMax||"1000000");const jobs=await request("/jobs?"+p.toString());setJobCatalog(jobs);setToast(`Found ${jobs.length} demo listing(s).`)}catch(e){setToast(e.message)}}
  async function saveJob(job){if(!token){setShowAuth(true);return}try{await request("/saved-jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job_id:job.id})},token);setToast("Job saved to your dashboard.")}catch(e){setToast(e.message)}}
  function toggleCompare(job){setCompared(prev=>prev.some(x=>x.id===job.id)?prev.filter(x=>x.id!==job.id):prev.length<3?[...prev,job]:(setToast("Compare up to three jobs at a time."),prev))}
  async function analyzeResume(e){e.preventDefault();setError("");try{let text=profile;if(resume){const form=new FormData();form.append("profile_text",profile);form.append("resume",resume);const r=await fetch(API+"/match",{method:"POST",body:form});const d=await r.json();if(!r.ok)throw Error(d.detail||"Resume extraction failed.");text=[profile,...(d.candidate_skills||[])].join(" ");}if(text.trim().length<10)throw Error("Enter profile details or upload a resume on the Job Matcher tab first.");setAnalysis(await request("/resume/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile_text:text})}));}catch(e){setError(e.message)}}
  async function makeRoadmap(e){e.preventDefault();try{setRoadmap(await request("/roadmap",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target_role:roadRole,current_skills:roadSkills.split(",").map(x=>x.trim()).filter(Boolean)})}))}catch(e){setError(e.message)}}
  async function makeInterview(e){e.preventDefault();try{setInterview(await request("/interview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role:interviewRole})}));setQuizAnswers({})}catch(e){setError(e.message)}}
  async function sendChat(e){e.preventDefault();if(!chatInput.trim())return;const msg=chatInput;setChatInput("");setChatMessages(prev=>[...prev,{from:"you",text:msg}]);try{const d=await request("/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:msg})});setChatMessages(prev=>[...prev,{from:"bot",text:d.reply}])}catch(err){setChatMessages(prev=>[...prev,{from:"bot",text:err.message}])}}
  async function loadDashboard(){if(!token){setShowAuth(true);return}try{const d=await request("/dashboard",{},token);setDashboard(d);setApplications(d.applications||[]);setTab("dashboard")}catch(e){setToast(e.message);setShowAuth(true)}}
  async function addApplication(e){e.preventDefault();if(!token){setShowAuth(true);return}try{const d=await request("/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job_title:appTitle,company:appCompany,status:appStatus,notes:""})},token);setApplications(prev=>[d,...prev]);setAppTitle("");setAppCompany("");setToast("Application added.")}catch(e){setToast(e.message)}}
  async function removeApplication(id){try{await request("/applications/"+id,{method:"DELETE"},token);setApplications(prev=>prev.filter(x=>x.id!==id))}catch(e){setToast(e.message)}}
  function handleAuth(d){localStorage.setItem("jm_token",d.token);setToken(d.token);setUser(d.user);setShowAuth(false);setToast("Signed in successfully.");}
  function logout(){localStorage.removeItem("jm_token");setToken("");setUser(null);setDashboard(null);setToast("Signed out.")}
  const shownMatches=useMemo(()=>matches.filter(j=>(!roleFilter||j.title.toLowerCase().includes(roleFilter.toLowerCase()))&&(!locationFilter||j.location.toLowerCase().includes(locationFilter.toLowerCase()))),[matches,roleFilter,locationFilter]);
  const selectedTab=(key)=>{if(key==="dashboard")loadDashboard();else setTab(key)};
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab("matcher")}}><span className="brand-mark">JM</span><span>Job<span className="brand-accent">Match</span><small>AI CAREER DISCOVERY</small></span></a><div className="account-area">{user?<><span className="user-pill"><UserRound size={15}/>{user.name}</span><button className="secondary-button" onClick={logout}><LogOut size={15}/> Sign out</button></>:<button className="secondary-button" onClick={()=>setShowAuth(true)}><LogIn size={16}/> Sign in</button>}</div></header>
    <nav className="feature-nav">{navItems.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>selectedTab(key)}>{label}</button>)}</nav>
    <main>
      {tab==="matcher"&&<><section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={14}/> CAREER DISCOVERY, REIMAGINED</span><h1>Your skills.<br/><span>Your next opportunity.</span></h1><p>Match your profile to jobs, understand skill gaps, improve your resume, and build a practical career plan.</p><div className="hero-points"><span><CheckCircle2 size={16}/> Explainable results</span><span><CheckCircle2 size={16}/> Resume PDF support</span><span><CheckCircle2 size={16}/> Career toolkit</span></div></div><div className="hero-visual"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><div className="visual-core"><BrainCircuit size={43}/></div><div className="float-card float-top"><FileText size={17}/><span><b>Resume insights</b><small>Skills and opportunities</small></span></div><div className="float-card float-bottom"><Sparkles size={17}/><span><b>Smart recommendations</b><small>Ranked by profile fit</small></span></div></div></section>
        <section className="workspace"><form className="profile-panel" onSubmit={findMatches}><div className="panel-heading"><span className="step">01</span><div><h2>Build your profile</h2><p>Share your skills, projects, or resume.</p></div></div><label htmlFor="profile">PROFILE DETAILS <span>Optional if uploading a resume</span></label><textarea id="profile" value={profile} onChange={e=>setProfile(e.target.value)} placeholder="I'm a computer science student skilled in Python, SQL, React and machine learning. I built a student performance prediction project…" rows={7}/><div className="upload-label"><label htmlFor="resume">UPLOAD RESUME <span>PDF · 5 MB max</span></label></div><label className="upload-zone" htmlFor="resume"><span className="upload-icon"><FileText size={21}/></span><span><b>{resume?resume.name:"Choose your resume PDF"}</b><small>{resume?"Selected file":"Click to browse your files"}</small></span><input id="resume" type="file" accept=".pdf,application/pdf" onChange={e=>setResume(e.target.files?.[0]||null)}/></label><button className="submit-button" disabled={loading}><span>{loading?"Analyzing profile…":"Find my matching jobs"}</span><Sparkles size={17}/></button>{error&&<div className="error-message">{error}</div>}<p className="privacy-note"><FileText size={14}/> Uploaded resume is processed for your request and not saved as a file by this demo.</p></form>
        <aside className="tips-panel"><div className="tips-head"><div className="tips-icon"><Target size={19}/></div><span>YOUR CAREER TOOLKIT</span></div><h3>One profile. More possibilities.</h3><p>Use these tools to turn your current skills into a plan.</p><ul>{navItems.slice(1,6).map(([k,l])=><li key={k}><CheckCircle2 size={16}/><button className="inline-link" onClick={()=>setTab(k)}>{l}</button></li>)}</ul><div className="how-box"><BrainCircuit size={20}/><div><b>How matching works</b><p>60% required-skill overlap + 40% text similarity. Scores are estimates, not hiring probabilities.</p></div></div></aside></section>
        {hasSearched&&<section className="results-section"><div className="results-title"><div><span className="eyebrow">YOUR RESULTS</span><h2>Best-fit opportunities</h2><p>Detected skills: {candidateSkills.join(", ")||"No known skills detected"}</p></div><span className="result-count">{shownMatches.length} matches</span></div><div className="filter-grid"><label>Filter role<input value={roleFilter} onChange={e=>setRoleFilter(e.target.value)} placeholder="e.g. Data"/></label><label>Filter location<input value={locationFilter} onChange={e=>setLocationFilter(e.target.value)} placeholder="e.g. Remote"/></label></div><div className="jobs-grid">{shownMatches.map(job=><JobCard key={job.id} job={job} onSave={saveJob} saved={false} onCompare={toggleCompare} compared={compared.some(x=>x.id===job.id)}/>)}</div>{compared.length>1&&<div className="compare-panel"><h3>Job comparison</h3><div className="compare-grid">{compared.map(j=><div key={j.id}><b>{j.title}</b><p>{j.company}</p><strong>{j.match_score}% match</strong><p>Matched: {j.matched_skills.join(", ")||"None"}</p><p>Missing: {j.missing_skills.join(", ")||"None"}</p></div>)}</div></div>}</section>}
        <section className="feature-grid"><button onClick={()=>setTab("resume")} className="feature-card"><FileText/><b>Resume & ATS analyzer</b><span>Find skill keywords and improvement opportunities.</span><ArrowRight size={16}/></button><button onClick={()=>setTab("roadmap")} className="feature-card"><GraduationCap/><b>Learning roadmap</b><span>Build a practical plan for your target role.</span><ArrowRight size={16}/></button><button onClick={()=>setTab("interview")} className="feature-card"><Mic/><b>Interview preparation</b><span>Practice questions and short quizzes.</span><ArrowRight size={16}/></button></section></>}
      {tab==="resume"&&<section className="feature-page"><PanelTitle icon={FileText} eyebrow="PROFILE IMPROVEMENT" title="Resume analyzer & ATS keyword check" description="Get a transparent heuristic review of skills, sections, and resume structure."/><form className="tool-form" onSubmit={analyzeResume}><label>Resume/profile text<textarea rows={7} value={profile} onChange={e=>setProfile(e.target.value)} placeholder="Paste resume text here, or go to Job Matcher and upload a PDF first."/></label><button className="submit-button"><Sparkles size={16}/> Analyze resume</button></form>{analysis&&<div className="analysis-results"><div className="metric-card"><span>Resume readiness estimate</span><strong>{analysis.resume_score}/100</strong><div className="track"><div className="track-fill" style={{width:analysis.resume_score+"%"}}/></div><small>{analysis.word_count} words · heuristic score, not a real ATS vendor score</small></div><h3>Detected skills</h3><Tags items={analysis.detected_skills}/><h3>Section checklist</h3><div className="section-checks">{Object.entries(analysis.sections).map(([k,v])=><span key={k} className={v?"checked":""}>{v?"✓":"○"} {k}</span>)}</div><h3>Suggestions</h3><ul>{analysis.suggestions.map(s=><li key={s}>{s}</li>)}</ul><p className="muted small">{analysis.disclaimer}</p></div>}{error&&<p className="error-message">{error}</p>}</section>}
      {tab==="roadmap"&&<section className="feature-page"><PanelTitle icon={GraduationCap} eyebrow="SKILL DEVELOPMENT" title="Personalized learning roadmap" description="Choose your target role and current skills to create a three-stage project-based plan."/><form className="tool-form two-col" onSubmit={makeRoadmap}><label>Target role<input required value={roadRole} onChange={e=>setRoadRole(e.target.value)} placeholder="e.g. Data Analyst"/></label><label>Skills you already know<input value={roadSkills} onChange={e=>setRoadSkills(e.target.value)} placeholder="Python, SQL, Git (comma separated)"/></label><button className="submit-button">Generate my roadmap <ArrowRight size={16}/></button></form>{roadmap&&<div className="roadmap-list">{roadmap.weeks.map(w=><article className="roadmap-step" key={w.week}><span className="step">W{w.week}</span><div><h3>{w.focus}</h3><Tags items={w.skills} variant="missing"/><p><b>Portfolio task:</b> {w.project}</p></div></article>)}<p className="muted small">{roadmap.note}</p></div>}</section>}
      {tab==="interview"&&<section className="feature-page"><PanelTitle icon={Mic} eyebrow="PRACTICE ROOM" title="Interview preparation" description="Generate starter questions, sample answer frameworks, and a short self-check quiz."/><form className="tool-form two-col" onSubmit={makeInterview}><label>Target role<input value={interviewRole} onChange={e=>setInterviewRole(e.target.value)} required placeholder="e.g. Python Developer"/></label><button className="submit-button">Prepare interview <ArrowRight size={16}/></button></form>{interview&&<><h3>Practice questions for {interview.role}</h3><div className="qa-list">{interview.questions.map((q,i)=><details key={q.question} className="qa-card"><summary><span>{String(i+1).padStart(2,"0")}</span>{q.question}</summary><p>{q.sample_answer}</p></details>)}</div><h3>Quick quiz</h3>{interview.quiz.map((q,i)=><div className="quiz-card" key={q.question}><b>{i+1}. {q.question}</b>{q.options.map((opt,j)=><label key={opt} className="quiz-option"><input type="radio" name={"quiz"+i} checked={quizAnswers[i]===j} onChange={()=>setQuizAnswers(p=>({...p,[i]:j}))}/>{opt}</label>)}{quizAnswers[i]!==undefined&&<p className={quizAnswers[i]===q.answer?"correct":"incorrect"}>{quizAnswers[i]===q.answer?"Correct!":"Not quite — review the options and try again."}</p>}</div>)}</>}</section>}
      {tab==="chat"&&<section className="feature-page"><PanelTitle icon={MessageCircle} eyebrow="CAREER COPILOT" title="AI career chatbot" description="Ask about resumes, learning priorities, interviews, and job-search strategy."/><div className="chat-window">{chatMessages.map((m,i)=><div key={i} className={"chat-bubble "+m.from}><span>{m.from==="bot"?"Career guide":"You"}</span><p>{m.text}</p></div>)}</div><form className="chat-compose" onSubmit={sendChat}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="e.g. How can I prepare for a Python internship?" maxLength="2000"/><button className="submit-button"><Send size={16}/> Send</button></form><p className="muted small">This version uses built-in guidance rules and does not call an external generative AI model. Job examples are fictional.</p></section>}
      {tab==="tracker"&&<section className="feature-page"><PanelTitle icon={Activity} eyebrow="JOB SEARCH ORGANIZER" title="Application tracker" description="Keep a private list of roles and move them through your application pipeline."/><form className="tool-form two-col" onSubmit={addApplication}><label>Job title<input required value={appTitle} onChange={e=>setAppTitle(e.target.value)} placeholder="Python Intern"/></label><label>Company<input required value={appCompany} onChange={e=>setAppCompany(e.target.value)} placeholder="Company name"/></label><label>Status<select value={appStatus} onChange={e=>setAppStatus(e.target.value)}>{["Saved","Applied","Interview","Rejected","Offer"].map(s=><option key={s}>{s}</option>)}</select></label><button className="submit-button"><Plus size={16}/> Add application</button></form>{!user&&<p className="muted">Sign in to save your application tracker across sessions.</p>}{applications.length>0?<div className="application-list">{applications.map(a=><article className="application-row" key={a.id}><div><b>{a.job_title}</b><p>{a.company} · {a.applied_date}</p></div><span className={"status status-"+a.status.toLowerCase()}>{a.status}</span><button className="icon-button" title="Delete application" onClick={()=>removeApplication(a.id)}><Trash2 size={16}/></button></article>)}</div>:<div className="empty-state"><CircleHelp/><div><b>No tracked applications yet</b><p>Add a role above. Sign in to store your list in your account.</p></div></div>}</section>}
      {tab==="dashboard"&&<section className="feature-page"><PanelTitle icon={UserRound} eyebrow="PERSONAL WORKSPACE" title="My dashboard" description="Your saved jobs, matching history, and application pipeline."/>{dashboard?<><div className="dashboard-welcome"><h3>Welcome, {dashboard.user.name}</h3><p>{dashboard.user.email}</p></div><div className="dashboard-columns"><div><h3>Saved jobs</h3>{dashboard.saved_jobs.length?dashboard.saved_jobs.map(j=><div className="application-row" key={j.id}><div><b>{j.title}</b><p>{j.company} · {j.location}</p></div><button className="icon-button" onClick={()=>request("/saved-jobs/"+j.id,{method:"DELETE"},token).then(loadDashboard)}><Trash2 size={15}/></button></div>):<p className="muted">Save jobs from your matching results.</p>}</div><div><h3>Recent profile history</h3>{dashboard.history.length?dashboard.history.map(h=><details className="history-item" key={h.id}><summary>{new Date(h.created_at+"Z").toLocaleString()}</summary><p>{h.profile.slice(0,240)}</p><p>{h.matches.length} match(es) saved</p></details>):<p className="muted">Run a match while signed in to keep a history entry.</p>}</div></div><h3>Application pipeline</h3>{applications.map(a=><div className="application-row" key={a.id}><div><b>{a.job_title}</b><p>{a.company}</p></div><span className="status">{a.status}</span></div>)}</>:<button className="submit-button" onClick={()=>setShowAuth(true)}>Sign in to view dashboard</button>}</section>}
      {tab==="jobs"&&<section className="feature-page"><PanelTitle icon={Search} eyebrow="DEMO LISTINGS" title="Explore job listings" description="Filter the included sample roles by skills, location, work mode, and salary band."/><div className="filter-form"><label>Role<input value={roleFilter} onChange={e=>setRoleFilter(e.target.value)} placeholder="e.g. Developer"/></label><label>Required skills (comma separated)<input value={skillFilter} onChange={e=>setSkillFilter(e.target.value)} placeholder="Python, SQL"/></label><label>Location<input value={locationFilter} onChange={e=>setLocationFilter(e.target.value)} placeholder="Remote, Hyderabad"/></label><label>Minimum annual salary (₹)<input type="number" value={salaryMin} onChange={e=>setSalaryMin(e.target.value)}/></label><label>Maximum annual salary (₹)<input type="number" value={salaryMax} onChange={e=>setSalaryMax(e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={remoteOnly} onChange={e=>setRemoteOnly(e.target.checked)}/> Remote only</label><button className="submit-button" onClick={searchJobs}>Apply filters <Search size={16}/></button></div><div className="jobs-grid catalog-grid">{jobCatalog.map(j=><article className="job-card" key={j.id}><h3>{j.title}</h3><p>{j.company} · {j.location}</p><p>{j.description}</p><Tags items={j.skills}/><p className="salary">₹{(j.salary_min/100000).toFixed(1)}–₹{(j.salary_max/100000).toFixed(1)} LPA · {j.work_mode}</p><button className="secondary-button" onClick={()=>saveJob(j)}><Bookmark size={15}/> Save job</button></article>)}</div><p className="muted small">Listings and salary bands are fictional illustrative demo data, not live vacancies or verified compensation.</p></section>}
    </main>
    <footer className="site-footer"><span>JobMatch · AI Career Discovery</span><span>Similarity scores are estimates, not hiring predictions. Demo listings are fictional.</span></footer>
    {showAuth&&<AuthPanel onAuth={handleAuth} onClose={()=>setShowAuth(false)}/>}
    {toast&&<div className="toast-message" role="status">{toast}<button onClick={()=>setToast("")}><X size={15}/></button></div>}
  </div>;
}
